// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.680
package section

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func Header(isLoggedIn bool, userName string) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<nav><div class=\"nav-wrapper\"><a class=\"brand-logo\" href=\"\"><img src=\"/static/img/logo.png\" alt=\"\"></a> <a href=\"#\" data-target=\"mobile-demo\" class=\"sidenav-trigger\"><i class=\"large material-icons appcolor-text text-type-dark\">menu</i></a><ul id=\"nav-mobile\" class=\"hide-on-med-and-down right\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if isLoggedIn {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<li><a href=\"#modal-settings\" class=\"header-settings-btn waves-effect waves-light btn-small   appcolor-text text-type-light\">settings<i class=\"material-icons right\">settings</i></a></li><li><a href=\"#\" class=\"header-logout-btn waves-effect waves-light btn-small   appcolor-text text-type-light\">sign out<i class=\"material-icons right\">logout</i></a></li>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<li><a href=\"#modal-login\" class=\"appcolor logo-main waves-effect waves-light btn-small modal-trigger  appcolor-text text-type-light\">sign in<i class=\"material-icons right\">login</i></a></li>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</ul></div></nav><ul id=\"mobile-demo\" class=\"sidenav\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if isLoggedIn {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<li><a href=\"#modal-settings\" class=\"header-settings-btn waves-effect waves-light btn-small  appcolor-text text-type-light\">settings <i class=\"material-icons right appcolor-text text-type-light mobile-material\">settings</i></a></li><li><a href=\"#\" class=\"header-logout-btn waves-effect waves-light btn-small   appcolor-text text-type-light\">sign out<i class=\"material-icons right appcolor-text text-type-light mobile-material\">logout</i></a></li>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<li><a href=\"#modal-login\" class=\"appcolor logo-main waves-effect waves-light btn-small modal-trigger  appcolor-text text-type-light\">sign in<i class=\"material-icons right appcolor-text text-type-light mobile-material\">login</i></a></li>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</ul>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if isLoggedIn {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<h1 class=\"appcolor-text text-type-dark\" id=\"app-home-header\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var2 string
			templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(userName)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/view/section/header.templ`, Line: 40, Col: 87}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(", ready to change your life?</h1>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<h1 class=\"appcolor-text text-type-dark\" id=\"app-home-header\">Become happy and confident with affirmations.</h1>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<p id=\"app-home-paragraph\" class=\"appcolor-text text-type-dark\">Click on a card below to start improving yourself.</p>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
