CREATE TABLE IF NOT EXISTS  user (
    id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    cards JSON NOT NULL,
    settings JSON NOT NULL,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    created DATETIME NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE
);
