// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.680
package component

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func ModalLogin() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<!-- Modal Structure --><div id=\"modal-login\" class=\"modal appcolor-text text-type-dark\"><div class=\"modal-content\"><img class=\"modal-login-img\" src=\"./static/img/sign_in_img.png\" alt=\"\"><h3 class=\"modal-login-title\">Please sign in</h3><br><br><script src=\"https://accounts.google.com/gsi/client\" async defer></script><div id=\"google_signin_button\"><div id=\"g_id_onload\" data-client_id=\"311450763505-5srjnc3n5g7oh72mpea4neht497o66uc.apps.googleusercontent.com\" data-context=\"signin\" data-ux_mode=\"popup\" data-login_uri=\"oauth\" data-auto_prompt=\"false\"></div><div class=\"g_id_signin\" data-type=\"standard\" data-shape=\"pill\" data-theme=\"filled_blue\" data-text=\"signin_with\" data-size=\"large\" data-logo_alignment=\"left\"></div></div><br><br></div><br></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
