// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.680
package component

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func ModalSettings() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<!-- Modal Structure --><div id=\"modal-settings\" class=\"modal appcolor-text text-type-dark\"><div class=\"modal-content\"><!-- Show affirmations random--><div class=\"switch\"><p class=\"modal-label\">Show affirmations randomly</p><label><input id=\"modal-settings-check-rand-affirm\" type=\"checkbox\"> <span class=\"lever\"></span></label></div><br><!-- Autoplay affimations --><div class=\"switch\"><p class=\"modal-label\">Autoplay affirmations</p><label><input id=\"modal-settings-check-autoplay\" type=\"checkbox\"> <span class=\"lever\"></span></label></div><br><!-- Autoplay affirm duration--><div class=\"input-field col s12\"><p class=\"modal-label\">Autoplay each affirmation duration</p><select id=\"modal-settings-select-autoplay-duration\"><option value=\"10\">10 Seconds</option> <option value=\"15\">15 Seconds</option> <option value=\"25\">25 Seconds</option> <option value=\"40\">40 Seconds</option> <option value=\"60\">60 Seconds</option> <option value=\"120\">120 Seconds</option></select></div><br></div><div class=\"modal-footer\"><a href=\"#!\" class=\"waves-effect waves-light btn-small modal-close  appcolor-text text-type-light\">OK<i class=\"material-icons right\">check</i></a></div><br></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
